const tg=window.Telegram?.WebApp;
if(tg){tg.ready();tg.expand();}
const H={'X-Telegram-Init-Data':tg?.initData||''};
const $=x=>document.getElementById(x);
const ASSET_FALLBACK='/webapp/assets/fallback.svg';
async function api(u,o={}){o.headers={...(o.headers||{}),...H,'Content-Type':'application/json'};const r=await fetch(u,o);let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`Ошибка ${r.status}`);return d}
function img(src,cls=''){return `<img class="${cls}" src="${src||ASSET_FALLBACK}" onerror="this.onerror=null;this.src='${ASSET_FALLBACK}'" loading="lazy">`}
function toast(s){const e=$('toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function openModal(s){$('sheet').innerHTML=s;$('modal').classList.add('open')}
function closeModal(){$('modal').classList.remove('open')}
function scrollToId(id){$(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
async function load(){
 try{const u=await api('/api/user');$('balance').textContent=`🪙 ${Number(u.coins).toLocaleString()}  ⭐ ${u.stars}`;$('name').textContent=u.first_name||'Игрок';$('level').textContent=`Уровень ${u.level} • ${u.xp} XP`;$('xpbar').style.width=(u.xp%100)+'%';$('premium').textContent=u.premium_until?'👑 PREMIUM':'FREE'}catch(e){console.warn(e)}
 try{const c=await api('/api/cases');$('cases').innerHTML=c.cases.map(x=>`<div class="card case-card"><button class="case-open" onclick="caseInfo(${x.id})">${img(x.image_url,'case-img')}<div class="case-body"><b>${x.name}</b><div class="case-price"><span class="price">🪙 ${Number(x.price_coins).toLocaleString()}</span><span class="pill">ОТКРЫТЬ</span></div></div></button></div>`).join('');
 let a=[];for(const x of c.cases){const d=await api('/api/cases/'+x.id+'/items');a.push(...d.items)}$('items').innerHTML=a.slice(0,49).map(i=>`<div class="item ${i.rarity.toLowerCase()}">${img(i.image_url)}<span>${i.name}</span></div>`).join('')}catch(e){toast('Не удалось загрузить кейсы')}
}
function openCases(){scrollToId('casesSection')}
async function caseInfo(id){try{const c=(await api('/api/cases')).cases.find(x=>x.id===id);const d=await api(`/api/cases/${id}/items`);openModal(`<div class="case-modal-head">${img(c?.image_url,'modal-case-img')}<div><h2>${c?.name||'Кейс'}</h2><p class="muted">${c?.description||'Эксклюзивный кейс VLDST CASE'}</p></div></div><div class="grid"><button class="primary" onclick="openCase(${id})">🪙 ${Number(c?.price_coins||0).toLocaleString()}</button><button class="primary stars-btn" onclick="buyCase(${id})">⭐ ${c?.price_stars||0}</button></div><h3>🎁 Содержимое</h3><div class="item-grid">${d.items.map(i=>`<div class="item ${i.rarity.toLowerCase()}">${img(i.image_url)}<span>${i.name}</span></div>`).join('')}</div>`)}catch(e){toast(e.message)}}
async function openCase(id){try{const d=await api(`/api/cases/${id}/open`,{method:'POST'});openModal(`<div class="result win"><div class="win-ring">🎉</div><h2>ВЫИГРЫШ!</h2>${img(d.item.image_url,'result-img')}<h2>${d.item.name}</h2><p class="rarity-${d.item.rarity.toLowerCase()}">${d.item.rarity}</p><p class="muted">Продажа: 🪙 ${Number(d.item.sell_price).toLocaleString()}</p><button class="primary" onclick="closeModal();load()">ЗАБРАТЬ</button></div>`);load()}catch(e){toast(e.message)}}
async function buyCase(id){try{const d=await api('/api/stars/invoice',{method:'POST',body:JSON.stringify({kind:'case',case_id:id})});if(tg?.openInvoice)tg.openInvoice(d.invoice_url);else window.open(d.invoice_url,'_blank')}catch(e){toast(e.message)}}
async function showShop(){openModal('<h2>⭐ Магазин VLDST</h2><p class="muted">Telegram Stars → Premium, бусты и пополнение баланса.</p><div id="shoplist">Загрузка...</div>');try{const d=await api('/api/shop');$('shoplist').innerHTML=`<h3>⭐ Баланс Stars</h3>${d.balance_products.map(p=>`<div class="card shop-row"><div><b>${p.title}</b><div class="muted">Внутренний баланс VLDST</div></div><button class="primary small" onclick="buyProduct('${p.id}','balance')">⭐ ${p.stars}</button></div>`).join('')}<h3>👑 Услуги</h3>${d.store_products.map(p=>`<div class="card shop-row"><div><b>${p.title}</b><div class="muted">${p.description}</div></div><button class="primary small" onclick="buyProduct('${p.id}','store')">⭐ ${p.stars}</button></div>`).join('')}`}catch(e){toast(e.message)}}
async function buyProduct(id,kind){try{const d=await api('/api/stars/invoice',{method:'POST',body:JSON.stringify({kind,product:id})});if(tg?.openInvoice)tg.openInvoice(d.invoice_url);else window.open(d.invoice_url,'_blank')}catch(e){toast(e.message)}}
async function showMini(){openModal('<div class="result"><div class="game-icon">🎮</div><h2>VLDST RUSH</h2><p class="muted">Каждая игра даёт случайный счёт и награду Coins.</p><button class="primary" onclick="play()">⚡ ИГРАТЬ</button><div id="game"></div></div>')}
async function play(){try{const d=await api('/api/minigame/play',{method:'POST'});$('game').innerHTML=`<div class="game-result"><b>Счёт: ${d.score}</b><strong>+${Number(d.reward).toLocaleString()} 🪙</strong></div>`;load()}catch(e){toast(e.message)}}
async function showRef(){try{const d=await api('/api/referrals');openModal(`<div class="result"><div class="game-icon">👥</div><h2>РЕФЕРАЛЫ</h2><p>Приглашено: <b>${d.count}</b></p><p class="muted">За каждого нового игрока начисляется 500 Coins.</p><input id="refLink" value="${d.referral_link}" readonly><button class="primary" onclick="navigator.clipboard?.writeText($('refLink').value);toast('Ссылка скопирована')">🔗 КОПИРОВАТЬ</button></div>`)}catch(e){toast(e.message)}}
async function showTasks(){try{const d=await api('/api/tasks');openModal(`<h2>🎯 Задания</h2>${d.tasks.map(t=>`<div class="card task-row"><div><b>${t.title}</b><p class="muted">${t.description}</p><span class="price">🪙 ${t.reward_coins||0} ${t.reward_stars?`⭐ ${t.reward_stars}`:''}</span></div><button class="primary small" onclick="claim(${t.id})" ${t.claimed?'disabled':''}>${t.claimed?'✓':'ЗАБРАТЬ'}</button></div>`).join('')||'<p class="muted">Новых заданий нет.</p>'}<button class="primary" style="margin-top:10px" onclick="claimDaily()">🎁 ЕЖЕДНЕВНАЯ НАГРАДА</button>`)}catch(e){toast(e.message)}}
async function claim(id){try{await api(`/api/tasks/${id}/claim`,{method:'POST'});toast('Награда получена');showTasks();load()}catch(e){toast(e.message)}}
async function claimDaily(){try{const d=await api('/api/daily',{method:'POST'});toast(`+${d.reward} Coins`);load()}catch(e){toast(e.message)}}
async function showInventory(){try{const d=await api('/api/inventory');openModal(`<h2>🎒 Инвентарь</h2><p class="muted">Все полученные предметы можно продать за Coins.</p><div class="item-grid">${d.inventory.map(i=>`<div class="item ${i.rarity.toLowerCase()}">${img(i.image_url)}<span>${i.name}<br><button class="pill" onclick="sell(${i.inventory_id})">🪙 ${Number(i.sell_price).toLocaleString()} ПРОДАТЬ</button></span></div>`).join('')||'<p class="muted">Инвентарь пуст.</p>'}</div>`)}catch(e){toast(e.message)}}
async function sell(id){try{const d=await api(`/api/inventory/${id}/sell`,{method:'POST'});toast(`Продано за ${Number(d.sold_for).toLocaleString()} Coins`);showInventory();load()}catch(e){toast(e.message)}}
async function showProfile(){try{const u=await api('/api/user');openModal(`<div class="profile-modal"><div class="avatar big">V</div><h2>${u.first_name||'Игрок'}</h2><p class="muted">@${u.username||'player'} • ID ${u.telegram_id}</p><div class="profile-stats"><div>🪙<b>${Number(u.coins).toLocaleString()}</b><small>Coins</small></div><div>⭐<b>${u.stars}</b><small>Stars</small></div><div>🏆<b>${u.level}</b><small>Level</small></div><div>⚡<b>${u.xp}</b><small>XP</small></div></div><div class="premium-box" id="premiumBox">${u.premium_until?'👑 Premium активен до '+new Date(u.premium_until).toLocaleString():'FREE аккаунт'}</div><div class="grid"><button class="primary" onclick="showInventory()">🎒 Инвентарь</button><button class="primary" onclick="showLeaderboard()">🏆 Рейтинг</button></div></div>`)}catch(e){toast(e.message)}}
async function showLeaderboard(){try{const d=await api('/api/leaderboard');openModal(`<h2>🏆 Рейтинг</h2>${d.leaderboard.map((u,i)=>`<div class="rank-row"><b>#${i+1}</b><span>${u.first_name||'Игрок'} ${u.username?`@${u.username}`:''}</span><strong>LVL ${u.level}</strong><span>${Number(u.xp).toLocaleString()} XP</span></div>`).join('')}`)}catch(e){toast(e.message)}}
async function showBoosts(){try{const d=await api('/api/boosts');openModal(`<h2>⚡ Мои бусты</h2>${d.boosts.map(b=>`<div class="card"><b>${b.type}</b><div class="muted">До ${new Date(b.expires_at).toLocaleString()}</div></div>`).join('')||'<p class="muted">Активных бустов нет.</p>'}<button class="primary" onclick="showShop()">⭐ ОТКРЫТЬ МАГАЗИН</button>`)}catch(e){toast(e.message)}}
$('modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
load();
